"""Add likes to answer

Revision ID: 8d2de6e8b5e3
Revises: 9ebff292809e
Create Date: 2024-03-12 00:52:03.246099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2de6e8b5e3'
down_revision: Union[str, None] = '9ebff292809e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'likes')
    # ### end Alembic commands ###
