default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: localhost
  port: 3306
  database: kzgiri
  username: kzgiri-client
  password: kzgiri
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV["KZGIRI_SERVER_DATABASE_HOST"] %>
  port: <%= ENV["KZGIRI_SERVER_DATABASE_PORT"] %>
  username: <%= ENV["KZGIRI_SERVER_DATABASE_USERNAME"] %>
  password: <%= ENV["KZGIRI_SERVER_DATABASE_PASSWORD"] %>
